In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
data = {
    'Action': [5, 4, 1, 2, 5, 1],
    'Comedy': [3, 5, 2, 1, 4, 2],
    'Drama':  [4, 2, 5, 4, 1, 5],
    'SciFi':  [5, 4, 2, 1, 5, 1],
    'Like':   [1, 1, 0, 0, 1, 0]   # Label
}

df = pd.DataFrame(data)
df

   Action  Comedy  Drama  SciFi  Like
0       5       3      4      5     1
1       4       5      2      4     1
2       1       2      5      2     0
3       2       1      4      1     0
4       5       4      1      5     1
5       1       2      5      1     0

In [18]:
df.corr()

          Action    Comedy     Drama     SciFi      Like
Action  1.000000  0.716115 -0.769800  0.944444  0.962250
Comedy  0.716115  1.000000 -0.785553  0.787726  0.868243
Drama  -0.769800 -0.785553  1.000000 -0.705650 -0.777778
SciFi   0.944444  0.787726 -0.705650  1.000000  0.962250
Like    0.962250  0.868243 -0.777778  0.962250  1.000000

In [6]:
X = df.drop('Like', axis=1)   # Features
y = df['Like']               # Label

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [10]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [12]:
y_pred = knn.predict(X_test)

In [14]:
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

Model Accuracy: 0.0

In [16]:
new_user = np.array([[4, 3, 4, 5]])  # Action, Comedy, Drama, SciFi

recommendation = knn.predict(new_user)

if recommendation[0] == 1:
    print("Movie Recommended 👍")
else:
    print("Movie Not Recommended 👎")

Movie Not Recommended 👎

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [20]:
import pandas as pd

# Suppose you downloaded and extracted the ml-100k data
ratings = pd.read_csv("ml-100k/u.data", sep="\t", names=["userId","movieId","rating","timestamp"])
print(ratings.head())

FileNotFoundError: [Errno 2] No such file or directory: 'ml-100k/u.data'

In [24]:
df = pd.read_csv("u1.base")
df

            1\t1\t5\t874965758
0           1\t2\t3\t876893171
1           1\t3\t4\t878542960
2           1\t4\t3\t876893119
3           1\t5\t3\t889751712
4           1\t7\t4\t875071561
...                        ...
79994  943\t1067\t2\t875501756
79995  943\t1074\t4\t888640250
79996  943\t1188\t3\t888640250
79997  943\t1228\t3\t888640275
79998  943\t1330\t3\t888692465

[79999 rows x 1 columns]